### ISSUE TITLE
Printing style

### ISSUE THREAD

**Issue by kariminf** [kariminf/cv.json#5]
Style the printing

```css 
@media print
{
    #exp, #educ, #pub, #skill {
        page-break-inside: avoid;
    }
}
```
